name: WhaleChan
version: 0.1.0.0
synopsis: KanColle game-related event reminder and staff account message re-posting bot.
description: See README at <https://github.com/Javran/WhaleChan#readme>
maintainer: Javran Cheng <javran.c@gmail.com>
github: Javran/WhaleChan
category: Telegram

dependencies:
  - aeson
  - async
  - authenticate-oauth
  - base
  - bytestring
  - conduit-extra
  - containers
  - data-default
  - data-ordlist
  - deepseq
  - dhall
  - directory
  - dlist
  - fast-logger
  - html-conduit
  - http-client
  - http-client-tls
  - http-types
  - lens
  - mime-types
  - monad-logger
  - mono-traversable
  - mtl
  - servant-client
  - tagsoup
  - telegram-api
  - terminfo
  - text
  - time
  - timezone-olson
  - timezone-series
  - twitter-conduit
  - twitter-types
  - unordered-containers
  - xml-conduit
  - yaml

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  WhaleChan:
    main: WhaleChan.hs
    source-dirs: exe
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is WhaleChan
    dependencies:
      - WhaleChan

tests:
  hspec:
    main: Spec.hs
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
    build-tools: hspec-discover
