resolver: lts-16.4

packages:
- .

extra-deps:
- git: https://github.com/Javran/haskell-telegram-api.git
  commit: 649480f5b414c24e08ae0159c925e8a097ec2d3b
- prettyprinter-1.6.0
- servant-http-streams-0.17
- servant-0.17
- servant-client-core-0.17
- twitter-conduit-0.5.0
- twitter-types-0.10.1
- twitter-types-lens-0.10.0

allow-newer: true
