resolver: lts-14.0

packages:
- .

extra-deps:
- git: https://github.com/Javran/twitter-conduit.git
  commit: d9e21188fb082390d4a91cdf74d4452c10146466
- git: https://github.com/Javran/haskell-telegram-api.git
  commit: 649480f5b414c24e08ae0159c925e8a097ec2d3b
- git: https://github.com/Javran/twitter-types.git
  commit: 04c052e33e5be2cba17b931773013a0c435e4fed
  subdirs:
    - twitter-types
    - twitter-types-lens
