resolver: lts-13.15

packages:
- .

extra-deps:
- git: https://github.com/Javran/twitter-conduit.git
  commit: d9e21188fb082390d4a91cdf74d4452c10146466
- git: https://github.com/Javran/haskell-telegram-api.git
  commit: d5a80a0d406bcae023fb48ad4204d8e72e546ad3
- git: https://github.com/Javran/twitter-types.git
  commit: a925e8520563b13a32cb3d6ee10251748714099e
  subdirs:
    - twitter-types
    - twitter-types-lens
